version: '3.8'

services:
  calibration:
    image: ghcr.io/tmolteno/tart_cal
    build: .                                # Path to Dockerfile
    environment:
      TART_LOGIN_PW: sharkbait                    # used for pushing new gains to API. Match to set in the telescope API.
      TART_API: https://tart.elec.ac.nz/signal/   # telescope API endpoint
      TARGET: signal
      TART_NCAL: 1                                # use 1 for debugging only
      TART_CAL_INT: 30                            # Interval between measurements
    volumes:
      - ~/calibration_results:/work
    command: /raw_calibrate.sh

